### ISSUE TITLE
genome builds and indexes

### ISSUE THREAD

**Issue by ericlarson84** [MOLB7621/Discussion#19]
I have a few questions.  I see that in class we are mostly working with the UCSC hg19 build, but there are others out there including NCBI and ENSEMBL (including multiple iterations of each).
Is there any benefit to using one vs the other?  ie if we used say NCBI GRCh38 instead of hg19 for problem set 4, we wouldn't expect to see any different results right?

Secondly, I see that through iGenomes you can download pre-indexed sequences and annotations ready to use for Bowtie.  Could that same index be used for another short read aligner (tophat, histat, etc).  Or would you have to download/create separate indexes using whichever aligner you want to use?

Hope the answers to these aren't crazy complicated!  I'm just trying to wrap my head around the plethora of information that exists on the web

**Comment by jayhesselberth** [comment]
There can be benefits of using some builds. For example, it takes time to move all of the data tracks from assembly to assembly, so usually the build before the more recent one has the most data. In UCSC, the hg19 assembly currently has more tracks (ENCODE data etc) than the hg38 assembly.

If you start with FASTQ and alignment (the problem set) then the assembly doesn't matter. However if you start with downstream files (BAM, BED etc) then the assembly absolutely does matter as the coordinate system changes because the chromosomes gain/lose/change sequence between assemblies. UCSC provides a tool called `liftOver` that lets you move coordinate systems (e.g. peaks in BED format) between assemblies.

Indices are not transferrable between aligners; you can't use a bowite2 index with bwa and vice versa. So as long as you have FASTA then you can make an index for the aligner you need.
