### ISSUE TITLE
Ideas for Final Projects

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/Discussion#21]
## Variants in DNase I hypersensitive sites

_Measure variation in DNase I hypersensitive sites._
1. Download [DHS](http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeRegDnaseClustered/wgEncodeRegDnaseClusteredV3.bed.gz) from ENCODE and tidy the data. This [file](http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeRegDnaseClustered/wgEncodeRegDnaseClusteredSources.tab) links IDs with cell types.
2. Download [dbSNP](http://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz) for hg19. Note this is a BIG download.
3. Cross-reference / count numbers of variants within DHS and identify possibly unique signatures of variation that distinguish cell types.

**Comment by donaldevans** [comment]
Jay

I am sorry I haven’t been in class.  I have gotten way behind because I had several doctor appointments that conflicted with class (first I injured my knee and then I was diagnosed with Type 1 Diabetes!) and I haven’t been able to get caught up.  I hope I have done enough to at least pass, but I think I’ll have to try this again the next time you teach it and can hopefully make all of the classes.  Thank you for your help (and that of the TAs).

Sincerely

Donnie

Donald Evans
Research Associate
Linda Crnic Institute for Down Syndrome
P15-4430 Mail Stop 8608
12700 E. 19th Ave.
Aurora, CO 80045
(303) 724-6886



On Apr 18, 2016, at 7:51 AM, Jay Hesselberth <notifications@github.com<mailto:notifications@github.com>> wrote:

Variants in DNase I hypersensitive sites

Measure variation in DNase I hypersensitive sites.

  1.  Download DHS<http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeRegDnaseClustered/wgEncodeRegDnaseClusteredV3.bed.gz> from ENCODE and tidy the data. This file<http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeRegDnaseClustered/wgEncodeRegDnaseClusteredSources.tab> links IDs with cell types.

  2.  Download dbSNP<http://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz> for hg19. Note this is a BIG download.

  3.  Cross-reference / count numbers of variants within DHS and identify possibly unique signatures of variation that distinguish cell types.

**Comment by johnsonrk2** [comment]
I have case-control methylation data on a bunch of kids at an important time point in T1D disease progression. Thinking to find DMRs using comb-p script in python, then create browser track with results as my final project. Are there bonus points for using Python? Secondly/more seriously, is this an appropriate scope for the project?

**Comment by jayhesselberth** [comment]
Seems like reasonable scope, as long as the result isn't p-values. Some kind of interpretation of significant loci / genes etc.
